close all;
missingData = randn(4,4,4,4);
interpData = randn(4,4,4,4);
knownSrcs = [1, 3; 2, 4];    % known sources are (1,2) and (3,4)
samplePoints = [1, 1; 1, 2]; % want to display sources (1,1) and (1,2)
upsampleRecs = 0;           % fourier upsampled grid to display figures on (set to 0 for no upsampling)
isPermuted = true;           % true if data is in [src x rec x src y rec y] format, false if data is in [src x src y rec x rec y] format
saveDir = [];                % directory to save figures in (empty if no figures are to be saved)
dispTitles = false;
axisLabels = true;

interpolation4dFigures(missingData,interpData,knownSrcs, ...
                       'saveDir',saveDir,...
                       'isPermuted',isPermuted,...
                       'dispTitles',dispTitles, ...
                       'axisLabels',axisLabels, ...
                       'samplePoints',samplePoints,...
                       'upsampleRecs',upsampleRecs);